name: Deploy Serverless
description: Deploy serverless stack to AWS

inputs:
  environment:
    description: 'Deployment environment (e.g., dev, prod)'
    required: true
  aws-region:
    description: 'AWS region to deploy to'
    required: true
  role-to-assume:
    description: 'AWS IAM role to assume for deployment'
    required: true
  artifact-key:
    description: 'S3 key for the deployment artifact'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Download artifact from S3
      shell: bash
      run: aws s3 cp s3://sg-puvilink-dev-sls-deployment-bucket-ap-south-1/${{ inputs.artifact-key }} app.zip
    - name: Unzip artifact
      shell: bash
      run: unzip app.zip
    - name: Deploy with Serverless
      shell: bash
      run: npx serverless deploy --stage ${{ inputs.environment }} --region ${{ inputs.aws-region }}
      # env:
      #   SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}