name: Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ../actions/build-node
      - uses: Puvilinktechnology/devops-workflows/.github/actions/build-node@master
        with:
          node-version: '22'
          pipelineDirectory: .
      - run: npm run test